### PR TITLE
DEVEXP-515: Adding credentialstores package.

### PR DESCRIPTION
**Pull request by ricardomaraschini**
This is a package that has been ported from openshift-apiserver. It is used on image-registry as well so it makes sense to have it in a single place and vendored in the others.

This package provides helpers for dealing with docker keyrings built from kubernetes secrets or node credentials.

### CODE REVIEW

**Comment by dmage** [comment]
/hold

nack, as for me, all these credential stores are mistake.

We should use https://github.com/kubernetes/kubernetes/blob/b342818361fe3f6613a79b6a7c8e520e53ecebb8/pkg/credentialprovider/secrets/secrets.go#L29

And we have a good example how to use it: https://github.com/kubernetes/kubernetes/blob/3c675ade250be481f26427aa9f38733b28bf2614/pkg/kubelet/kuberuntime/kuberuntime_image.go#L38-L44

**Comment by adambkaplan** [comment]
@dmage I'm reluctant to vendor in k8s.io/kubernetes. That will turn into a transitive dep nightmare for downstream libraries/projects.

**Comment by dmage** [comment]
@adambkaplan credential stores are built on top of k8s.io/kubernetes, so it means nack from you too.

**Comment by ricardomaraschini** [comment]
About using packages provided by k8s we kinda already do, as this is just a wrapper around them. The problem of using them directly is to understand the impact of removing the extra attempts we do to find credentials based on the [URL](https://github.com/ricardomaraschini/runtime-utils/blob/credentialstore-pkg/pkg/credentialstores/common.go#L26-L46) and [ports](https://github.com/ricardomaraschini/runtime-utils/blob/credentialstore-pkg/pkg/credentialstores/common.go#L49-L63), i think they have a reason to exist on the first place and to simply remove them might cause other issues.

**Comment by dmage** [comment]
`auth.docker.io/token` shouldn't be a special case, if you have it in your code, you are doing something wrong.

`index.docker.io` and `docker.io` aliasing is handled by https://github.com/kubernetes/kubernetes/blob/b342818361fe3f6613a79b6a7c8e520e53ecebb8/pkg/credentialprovider/keyring.go#L148

I'm fine if we don't implement this ports logic in new components, kubelet doesn't do it, the registry can skip it too.

**Comment by ricardomaraschini** [comment]
back to the whiteboard.

**Pull request closed without merging**
