### PR TITLE
bump api, module go version

### PR DESCRIPTION
**Pull request by QiWang19**
Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

**Comment by mtrmac** [comment]
/lgtm
/approve

Thanks!

**Comment by mtrmac** [comment]
@QiWang19 
> tide Pending — Not mergeable. Should not have do-not-merge/work-in-progress label.

**Comment by QiWang19** [comment]
@mtrmac This is ready to get merged.

**Pull request merged**
